title: Jared Branch, Ph.D.
author: Jared Branch
email: Jared.Branch@avila.edu
description: > # this means to ignore newlines until "baseurl:"
Dr. Jared Branch. Assistant Professor. Department of Psychology & Cognitive Science. Avila University. 
Memory. Future Thinking. Counterfactual Thinking. Pedagogy.
theme: primer
# social links

show_excerpts: true # set to false to remove excerpts on the homepage
